#!/bin/bash
echo "#################################################"                                               
echo "#                                               #"
echo "#             oracle                            #"
echo "#             DataGard auto install             #"
echo "#                                               #"
echo "#                                               #"
echo "#                                               #"
echo "#################################################"


####modified your init
ORACLE_SID=orcl
ORACLE_BASE=/home/oracle/app
ORACLE_HOME=$ORACLE_BASE/oracle/product/11.2.0/dbhome_1
DB_NAME=orcl
P_IP=192.168.30.118
S_IP=192.168.30.115
P_B_UNIQUE_NAME=primary
S_B_UNIQUE_NAME=standby
##oracle sys passwd
sys_pwd=oracle
root_pwd=oracle
oracle_pwd=oracle

set_host(){
cat &gt;&gt; /etc/hosts &lt;&lt; EOF
$P_IP	$P_B_UNIQUE_NAME
$S_IP	$S_B_UNIQUE_NAME
EOF
}

set_host

sendhost(){
expect -c "
           spawn scp -r /etc/hosts root@$S_IP:/etc
           expect {
               yes/no { send \"yes\r\"; exp_continue }
               *assword* { send \"$root_pwd\r\" }
           };
           expect 100% ;
           expect eof ;
       "
}
sendhost

sleep 3s
alterforce(){
alterlogging=$(
su - oracle -c "sqlplus -S / as sysdba &lt;&lt; !
set trimspool on feedback off  pagesize 0 heading off
alter database force logging;
exit;
!
"
)
}

alterarchivelog(){
alteralterarchivelog=$(
su - oracle -c "sqlplus -S / as sysdba &lt;&lt; !
set trimspool on feedback off  pagesize 0 heading off
alter database archivelog;
alter database open;
exit;
!
"
)
}

shutoracle(){
Shut_Oracle_Down=$(
su - oracle -c "sqlplus -S / as sysdba &lt;&lt; !
set trimspool on feedback off pagesize 0 heading off
shutdown immediate;
exit;
!
"
)
echo $Shut_Oracle_Down | grep "ORACLE instance shut down"
if [ $? -eq 0 ];then
        echo "Instacne Shutdown Successfully!"
else
        echo "Instacne still open, please shutdown manual(you have two minute to shutdown the database!)"
        sleep 120s
fi
}

mountoracle(){
Mount_Oracle=$(
su - oracle -c "sqlplus -S / as sysdba &lt;&lt; !
set trimspool on feedback off pagesize 0 heading off
startup mount;
exit;
!
"
)
echo $Mount_Oracle | grep "Database mounted"
if [ $? -eq 0 ];then
        echo "Database Mounted Successfully!"
fi
}

chkmount(){
mountstat=$(
su - oracle -c "sqlplus -S / as sysdba &lt;&lt; !
set trimspool on feedback off  pagesize 0 heading off
select status from v\\\$instance;
exit;
!
"
)
}

####开始查看是否启用force logging

echo "check force logging"
force_logging=$(
su - oracle -c "sqlplus -S / as sysdba &lt;&lt; !
set trimspool on feedback off  pagesize 0 heading off
select force_logging from v\\\$database;
exit;
!
"
)

if [ "$force_logging" == "NO" ];then
    echo "force logging is NO"
    echo "starting alter database force logging"
    alterforce
else
    echo "force logging is enabled"
fi

recovery_file(){
Recovery_file=$(
su - oracle -c "sqlplus -S / as sysdba &lt;&lt; !
! mkdir -p $ORACLE_BASE/fast_recovery_area;
alter system set db_recovery_file_dest_size=50G;
alter system set db_recovery_file_dest='$ORACLE_BASE/fast_recovery_area';
show parameter recovery;
exit;
!
"
)
echo $Recovery_file
}

recovery_file


# standby redo  logfile
redo_logfile(){
Redo_logfile=$(
su - oracle -c "sqlplus -S / as sysdba &lt;&lt; !
alter database add standby logfile '$ORACLE_BASE/oradata/$ORACLE_SID/stdredo01.log' size 50M;
alter database add standby logfile '$ORACLE_BASE/oradata/$ORACLE_SID/stdredo02.log' size 50M;
alter database add standby logfile '$ORACLE_BASE/oradata/$ORACLE_SID/stdredo03.log' size 50M;
alter database add standby logfile '$ORACLE_BASE/oradata/$ORACLE_SID/stdredo04.log' size 50M;
exit;
!
"
)
echo "standby redo  logfile ..."
echo $Redo_logfile

}

redo_logfile


register(){
su - oracle -c "sqlplus -S / as sysdba &lt;&lt; !
set trimspool on feedback off pagesize 0 heading off
alter system register;
exit;
!
"
}
register &gt;&gt; /home/oracle/dg.log 2&gt;&1


crpfile(){
su - oracle -c "sqlplus -S / as sysdba &lt;&lt; !
set trimspool on feedback off  pagesize 0 heading off
create pfile='/home/oracle/initorcl.ora' from spfile;
exit;
!
"
}

crpfile &gt;&gt; /home/oracle/dg.log 2&gt;&1


cp -p /home/oracle/initorcl.ora /home/oracle/initstandby.ora

#追加如下内容

insersp(){
cat &gt;&gt; /home/oracle/initorcl.ora &lt;&lt; EOF
*.db_unique_name=$P_B_UNIQUE_NAME
*.log_archive_config='dg_config=($P_B_UNIQUE_NAME,$S_B_UNIQUE_NAME)'
*.log_archive_dest_1='location=USE_DB_RECOVERY_FILE_DEST valid_for=(all_logfiles,all_roles) db_unique_name=$P_B_UNIQUE_NAME'
*.log_archive_dest_2='service=$S_B_UNIQUE_NAME valid_for=(online_logfiles,primary_role) lgwr async db_unique_name=$S_B_UNIQUE_NAME'
*.log_archive_dest_state_1=enable
*.log_archive_dest_state_2=enable
*.standby_file_management='auto'
*.fal_server=$S_B_UNIQUE_NAME
*.db_file_name_convert='$ORACLE_BASE/oradata/orcl','$ORACLE_BASE/oradata/orcl'
*.log_file_name_convert='$ORACLE_BASE/oradata/orcl','$ORACLE_BASE/oradata/orcl'
EOF
}

insersp &gt;&gt; /home/oracle/dg.log 2&gt;&1

cstdpfile(){
cat &gt;&gt; /home/oracle/initstandby.ora &lt;&lt; EOF
*.db_unique_name=$S_B_UNIQUE_NAME
*.audit_file_dest='$ORACLE_BASE/admin/orcl/adump'
*.log_archive_config='dg_config=($P_B_UNIQUE_NAME,$S_B_UNIQUE_NAME)'
*.log_archive_dest_1='location=USE_DB_RECOVERY_FILE_DEST valid_for=(all_logfiles,all_roles) db_unique_name=$S_B_UNIQUE_NAME'
*.log_archive_dest_2='service=$P_B_UNIQUE_NAME valid_for=(online_logfiles,primary_role) lgwr async db_unique_name=$P_B_UNIQUE_NAME'
*.log_archive_dest_state_1=enable
*.log_archive_dest_state_2=enable
*.standby_file_management='auto'
*.fal_server=$P_B_UNIQUE_NAME
*.db_file_name_convert='$ORACLE_BASE/oradata/orcl','$ORACLE_BASE/oradata/orcl'
*.log_file_name_convert='$ORACLE_BASE/oradata/orcl','$ORACLE_BASE/oradata/orcl'
EOF
}

cstdpfile &gt;&gt; /home/oracle/dg.log 2&gt;&1


###持久化参数文件
echo
echo "update pfile..."
usepfile(){
su - oracle -c "sqlplus -S / as sysdba &lt;&lt; !
set trimspool on feedback off  pagesize 0 heading off
shutdown immediate;
startup pfile='/home/oracle/initorcl.ora';
create spfile from pfile='/home/oracle/initorcl.ora';
exit;
!
"
}

usepfile &gt;&gt; /home/oracle/dg.log 2&gt;&1

####开始查看是否启用archivelog
echo
echo "check archivelog..."
archivelog=$(
su - oracle -c "sqlplus -S / as sysdba &lt;&lt; !
set trimspool on feedback off  pagesize 0 heading off
select LOG_MODE from v\\\$database;
exit;
!
"
)

if [ "$archivelog" == "NOARCHIVELOG" ];then
    echo "archivelog is NO"
    echo "please alter database archivelog"
    chkmount
    if [ "mountstat" == "MOUNTED" ];then
        alterarchivelog
    else
        shutoracle
        mountoracle
        alterarchivelog
    fi
elif [ "$archivelog" == "ARCHIVELOG" ];then
    echo "archivelog is enabled"
fi

#########现在是open

sendpfile(){
expect -c "
           spawn scp /home/oracle/initstandby.ora oracle@$S_IP:$ORACLE_HOME/dbs/initstandby.ora
           expect {
               yes/no { send \"yes\r\"; exp_continue }
               *assword* { send \"$oracle_pwd\r\" }
           };
           expect 100% ;
           expect eof ;
       "
}


mkd_1(){
expect -c "
           spawn ssh oracle@$S_IP
           expect {
               yes/no { send \"yes\r\"; exp_continue }
               *assword* { send \"$oracle_pwd\r\" }
           } ;
           expect ] { send \"mkdir -p $ORACLE_BASE/oradata/orcl \r\" };
           expect ] { send \"mkdir -p $ORACLE_BASE/admin/orcl/adump \r\" };
           expect ] { send \"mkdir -p $ORACLE_BASE/fast_recovery_area/$ORACLE_SID \r\" };
           expect eof ;
       "
}

echo
echo "mk sys passwd..."
sys_passwd(){
su - oracle -c " 
orapwd file=$ORACLE_HOME/dbs/orapworcl password=$sys_pwd force=y
"
}
sys_passwd

sendpasswd(){
expect -c "
           spawn ssh oracle@$S_IP
           expect {
               yes/no { send \"yes\r\"; exp_continue }
               *assword* { send \"$oracle_pwd\r\" }
           };
           expect ] { send \"orapwd file=$ORACLE_HOME/dbs/orapworcl password=$sys_pwd force=y \r\" };
           expect eof ;
       "
}

echo
echo "mkdir standby for standby"
echo
sleep 3s
mkd_1 &gt;&gt; /home/oracle/dg.log 2&gt;&1

echo "send orapw file to standby"
echo
sleep 3s
sendpasswd &gt;&gt; /home/oracle/dg.log 2&gt;&1

echo "send pfile to standby"
echo
sleep 3s
sendpfile &gt;&gt; /home/oracle/dg.log 2&gt;&1





# listener.ora..
echo "SID_LIST_LISTENER =
(SID_LIST =
 (SID_DESC =
   (GLOBAL_DBNAME = orcl)
   (ORACLE_HOME = $ORACLE_HOME)
   (SID_NAME = $ORACLE_SID)
 )
)" &gt;&gt; $ORACLE_HOME/network/admin/listener.ora

su - oracle -c "cp $ORACLE_HOME/network/admin/listener.ora $ORACLE_HOME/network/admin/listener.ora.std"

echo "
LISTENER =
(DESCRIPTION_LIST =
 (DESCRIPTION =
  (ADDRESS = (PROTOCOL = TCP)(HOST = $S_IP)(PORT = 1521))
 )
) " &gt;&gt; $ORACLE_HOME/network/admin/listener.ora.std

cp_listener(){
Cp_listener=$(expect -c "
           spawn scp $ORACLE_HOME/network/admin/listener.ora.std oracle@$S_IP:$ORACLE_HOME/network/admin/listener.ora
           expect {
               yes/no { send \"yes\r\"; exp_continue }
               *assword* { send \"$oracle_pwd\r\" }
           };
           expect 100%;
           expect eof ;
       "
)
echo $Cp_listener
}

cp_listener

echo "add tns"
#tns
echo "
$P_B_UNIQUE_NAME =
(DESCRIPTION =
 (ADDRESS_LIST =
  (ADDRESS = (PROTOCOL = TCP)(HOST = $P_IP)(PORT = 1521))
 )
 (CONNECT_DATA =
  (SERVICE_NAME = orcl)
 )
)

$S_B_UNIQUE_NAME=
 (DESCRIPTION =
  (ADDRESS_LIST =
   (ADDRESS = (PROTOCOL = TCP)(HOST = $S_IP)(PORT = 1521))
  )
  (CONNECT_DATA =
   (SERVICE_NAME = orcl)
  )
 )
" &gt;&gt; $ORACLE_HOME/network/admin/tnsnames.ora 

# lsnrctl status....
lsnrctl_s(){
Lsnrctl_s=$(
su - oracle -c "lsnrctl reload"
su - oracle -c "lsnrctl status"
)
}
lsnrctl_s

sendtns(){
expect -c "
           spawn scp $ORACLE_HOME/network/admin/tnsnames.ora oracle@$S_IP:$ORACLE_HOME/network/admin/tnsnames.ora
           expect {
               yes/no { send \"yes\r\"; exp_continue }
               *assword* { send \"$oracle_pwd\r\" }
           };
           expect 100%
           expect eof ;
       "
}

echo "send tns to standby"
sendtns &gt;&gt; /home/oracle/dg.log 2&gt;&1

#sleep 10s
#

crlisten_std(){
Crlisten_std=$(expect -c "
           spawn ssh oracle@$S_IP
           expect {
               yes/no { send \"yes\r\"; exp_continue }
               *assword* { send \"$oracle_pwd\r\" }
           } ;
expect ] { send \"lsnrctl start \r\" };
expect eof ;
"
)
}
crlisten_std


crspfiel_std(){
Crspfiel_std=$(expect -c "
           spawn ssh oracle@$S_IP
           expect {
               yes/no { send \"yes\r\"; exp_continue }
               *assword* { send \"$oracle_pwd\r\" }
           } ;
expect ] { send \"sqlplus / as sysdba \r\" };
expect SQL&gt;  { send \"create spfile from pfile='$ORACLE_HOME/dbs/initstandby.ora';\r\" };
expect SQL&gt;  { send \"startup nomount;\r\" };
expect SQL&gt;  { send \"exit;\r\" };

           expect eof ;
"
)
echo $Crspfiel_std
}
crspfiel_std

echo
echo "start to duplicate..."
dup_std(){
Dup_std=$(
su - oracle -c "rman target sys/123456@primary auxiliary sys/123456@standby &lt;&lt; !
run { 
duplicate target database for standby from active database nofilenamecheck dorecover;          
}
exit;
!
"
)
echo $Dup_std &gt;&gt; /home/oracle/dg.log 2&gt;&1 |grep "ERROR MESSAGE STACK FOLLOWS"
if [ $? -eq 0 ];then
        echo " Duplicate Faltrue!"
else
        echo " Duplicate Successfully!"
fi
}
dup_std

echo
expect -c "
           spawn ssh oracle@$S_IP
           expect {
               yes/no { send \"yes\r\"; exp_continue }
               *assword* { send \"$oracle_pwd\r\" }
           } ;
           expect ] { send \"sqlplus / as sysdba \r\" };
expect SQL&gt;  { send \"alter database open;\r\" };
expect SQL&gt;  { send \"alter database recover managed standby database using current logfile disconnect from session;\r\" };
expect SQL&gt;  { send \"select DATABASE_ROLE,OPEN_MODE from v\\\$database;\r\" };
set timeout 3
expect 888
expect SQL&gt;  exit
           expect eof ;
           
"
